server:
  port: 9090
  
spring:
  application:
    name: zuul-proxy
    
zuul:
  prefix: /app
  routes:
    test-redirect:
      path: /redirect/**
      location: http://www.google.co.in
    by-host:
      path: /demohost/**
      location: http://localhost:8081
    by-service:
      path: /test-service/**
      location: emp-service
    by-ribbon:
      path: /lb/**
      location: hr-service
      